_wandb:
    value:
        cli_version: 0.21.1
        e:
            017wayicrjvceji1k79yeajivuc4y8z5:
                args:
                    - --config
                    - configs/cifar100_resnet50.yaml
                codePath: scripts/parallel_dcl_nscl_train_simclr.py
                codePathLocal: scripts/parallel_dcl_nscl_train_simclr.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "409930686464"
                        used: "60654993408"
                email: priyadarsimishra@tamu.edu
                executable: /home/priyadarsimishra/anaconda3/envs/contrastive/bin/python
                git:
                    commit: 13152369f1ffaae8db12b723dbad58899a0750cf
                    remote: https://github.com/DLFundamentals/understanding_ssl_v2.git
                gpu: NVIDIA H100 NVL
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-041c541b-6dcf-f2a6-1259-8d701d973384
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-a98f3fdb-ad45-b66d-3ff7-27a99f03432e
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-fb51941f-b1a9-44da-13a7-9c701dbf59b5
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-86e46df3-6fca-376e-2cc1-3fbc0d906ed9
                host: csce-galanti-s1.engr.tamu.edu
                memory:
                    total: "1217102843904"
                os: Linux-6.14.0-28-generic-x86_64-with-glibc2.39
                program: /home/priyadarsimishra/understanding_ssl_v2/scripts/parallel_dcl_nscl_train_simclr.py
                python: CPython 3.10.18
                root: /home/priyadarsimishra/understanding_ssl_v2
                startedAt: "2025-08-26T17:13:18.799002Z"
                writerId: 017wayicrjvceji1k79yeajivuc4y8z5
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
            "2":
                - 1
                - 41
                - 49
                - 51
            "3":
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
augment_both:
    value: true
batch_size:
    value: 1024
dataset_name:
    value: cifar100
encoder_type:
    value: resnet50
experiment_name:
    value: simclr/cifar100
hidden_dim:
    value: 2048
lr:
    value: 0.3
projection_dim:
    value: 128
temperature:
    value: 0.1
width_multiplier:
    value: 1
world_size:
    value: 1
