experiment_name: "simclr/cifar100"
method_type: "simclr"
supervision: "DCL"

dataset:
  name: "cifar100"
  path: "./data/"
  num_output_classes: 100

training:
  batch_size: 1024
  num_epochs: 2501
  lr: 0.3
  augmentations_type: "cifar"
  augment_both: True
  save_every: 200
  log_every: 50
  track_performance: True
  multi_gpu: False
  world_size: 1

model:
  encoder_type: "resnet50"
  pretrained: False
  width_multiplier: 1
  hidden_dim: 2048
  projection_dim: 128

loss:
  temperature: 0.1

evaluation:
  checkpoints_dir: "checkpoints/cifar100_parallel/"
  perform_rsa: True
  perform_cka: True
  perform_cdnv: True
  perform_nccc: True
  perform_linear: False
  perform_tsne: False

linear:
  batch_size: 256
  num_epochs: 100
  num_output_classes: 10
  augment_both: False
  top_lr: 3e-4
  momentum: 0.9
  weight_decay: 5e-4
  track_performance: False
  save_every: 10